/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package  com.ford.fordpass.stacks;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
